// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhHePGkzHVOcfifSGRom4O95PGz4r7p1Q',
    appId: '1:885441245906:web:70a02793e4fa7cc85ab30b',
    messagingSenderId: '885441245906',
    projectId: 'avaliacao-mvp20252',
    authDomain: 'avaliacao-mvp20252.firebaseapp.com',
    storageBucket: 'avaliacao-mvp20252.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJaUnWgAXoVs2pGE6oyX0FGNb8w_OCeUE',
    appId: '1:885441245906:android:7f155f381de953885ab30b',
    messagingSenderId: '885441245906',
    projectId: 'avaliacao-mvp20252',
    storageBucket: 'avaliacao-mvp20252.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7T3NUp6liIfineI9mSwRRI1jA7S0vut8',
    appId: '1:885441245906:ios:8827234c351b0e8c5ab30b',
    messagingSenderId: '885441245906',
    projectId: 'avaliacao-mvp20252',
    storageBucket: 'avaliacao-mvp20252.firebasestorage.app',
    iosBundleId: 'br.dev.yago.avaliacaoMvp',
  );
}
